---
- name: Install Hammer and plugins
  ansible.builtin.package:
    name: "{{ hammer_packages }}"

- name: Configure Hammer Foreman plugin
  ansible.builtin.template:
    src: cli.modules.d-foreman.yml.j2
    dest: /etc/hammer/cli.modules.d/foreman.yml
    owner: root
    group: root
    mode: '0644'

- name: 'Add hammer module config directory'
  ansible.builtin.file:
    path: '/root/.hammer/cli.modules.d'
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: 'Configure Hammer Root Credentials file'
  ansible.builtin.template:
    src: hammer-root.yml.j2
    dest: /root/.hammer/cli.modules.d/foreman.yml
    owner: root
    group: root
    mode: '0600'
