---
- name: Setup quadlet demo machine
  hosts:
    - quadlet
  become: true
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/{{ certificate_source }}_certificates.yml"
    - "../../vars/images.yml"
    - "../../vars/database.yml"
    - "../../vars/foreman.yml"

  vars:
    certificates_hostnames:
      - "{{ ansible_fqdn }}"
      - localhost
    certificates_ca_password: "CHANGEME"
    candlepin_keystore_password: "CHANGEME"
    candlepin_oauth_secret: "CHANGEME"
    candlepin_ca_key_password: "{{ ca_key_password }}"
    candlepin_ca_key: "{{ ca_key }}"
    candlepin_ca_certificate: "{{ ca_certificate }}"
    candlepin_tomcat_key: "{{ localhost_key }}"
    candlepin_tomcat_certificate: "{{ localhost_certificate }}"
    candlepin_client_key: "{{ client_key }}"
    candlepin_client_certificate: "{{ client_certificate }}"
    foreman_ca_certificate: "{{ server_ca_certificate }}"
    foreman_client_key: "{{ client_key }}"
    foreman_client_certificate: "{{ client_certificate }}"
    foreman_oauth_consumer_key: abcdefghijklmnopqrstuvwxyz123456
    foreman_oauth_consumer_secret: abcdefghijklmnopqrstuvwxyz123456
    foreman_url: "https://{{ ansible_fqdn }}"
    httpd_server_ca_certificate: "{{ server_ca_certificate }}"
    httpd_client_ca_certificate: "{{ client_ca_certificate }}"
    httpd_server_certificate: "{{ server_certificate }}"
    httpd_server_key: "{{ server_key }}"
    pulp_content_origin: "https://{{ ansible_fqdn }}"
    pulp_pulp_url: "https://{{ ansible_fqdn }}"
  pre_tasks:
    - name: Deploy debug_tools
      ansible.builtin.include_role:
        name: debug_tools
    - name: Install podman
      ansible.builtin.package:
        name:
          - podman
    - name: Install other dependencies
      ansible.builtin.package:
        name:
          - bash-completion
          - python3-cryptography
          - python3-libsemanage
          - python3-psycopg2
          - python3-requests
  roles:
    - role: checks
    - role: certificates
      when: "certificate_source == 'default'"
    - role: certificate_checks
      vars:
        certificate_checks_certificate: "{{ server_certificate }}"
        certificate_checks_key: "{{ server_key }}"
        certificate_checks_ca: "{{ ca_certificate }}"
    - role: postgresql
      when:
        - database_mode == 'internal'
    - redis
    - candlepin
    - httpd
    - pulp
    - foreman
    - post_install

  handlers:
    - name: restart candlepin
      ansible.builtin.systemd:
        name: candlepin
        state: restarted

    - name: restart httpd
      ansible.builtin.systemd:
        name: httpd
        state: restarted

    - name: restart pulp-api
      ansible.builtin.systemd:
        name: pulp-api
        state: restarted

    - name: restart pulp-content
      ansible.builtin.systemd:
        name: pulp-content
        state: restarted

    - name: restart pulp-worker
      ansible.builtin.systemd:
        name: pulp-worker
        state: restarted

    - name: restart foreman
      ansible.builtin.systemd:
        name: foreman
        state: restarted

    - name: restart dynflow-sidekiq@orchestrator
      ansible.builtin.systemd:
        name: dynflow-sidekiq@orchestrator
        state: restarted

    - name: restart dynflow-sidekiq@worker
      ansible.builtin.systemd:
        name: dynflow-sidekiq@worker
        state: restarted

    - name: restart dynflow-sidekiq@worker-hosts-queue
      ansible.builtin.systemd:
        name: dynflow-sidekiq@worker-hosts-queue
        state: restarted

    - name: restart postgresql
      ansible.builtin.systemd:
        name: "{{ postgresql_container_name | default('postgresql') }}"
        state: restarted
